name: Spellerino
on: [workflow_dispatch]
jobs:
  code-spell:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Run codespell
      uses: codespell-project/actions-codespell@master
      with:
        skip: ./.git
        ignore_words_list: tanstaafl
